// eslint-disable-next-line
export default[
  {
    "id": 1,
    "name": "Margherita Pizza",
    "price": 199.50,
    "image": "https://www.engelvoelkers.com/wp-content/uploads/2014/07/pizza-stock.jpg",
    quantity: 1,
  },
  {
    "id": 2,
    "name": "Classic Burger",
    "price": 99.00,
    "image": "https://i0.wp.com/thenutritionadventure.com/wp-content/uploads/2017/07/PourHouseAmericanBurger.jpg?resize=5236%2C3490",
    quantity: 1,
  },
  {
    "id": 3,
    "name": "Age Roll",
    "price": 100.00,
    "image": "https://tse4.mm.bing.net/th?id=OIP.LKxzPBKYuBR_2tFwuBh98QHaF3&pid=Api&P=0&h=180",
    quantity: 1,
  },
  {
    "id": 4,
    "name": "Thali full Punjabi",
    "price": 250.00,
    "image": "https://en-media.thebetterindia.com/uploads/2016/08/guj-Copy.jpeg",
    quantity: 1,
  },
  {
    "id": 5,
    "name": "Maggi",
    "price": 65.50,
    "image": "https://i0.wp.com/dishesandflavors.com/wp-content/uploads/2021/01/Veg-Chow-Mein.jpg?resize=800%2C600&ssl=1&is-pending-load=1",
    quantity: 1,
  },
  {
    "id": 6,
    "name": "Caesar  Fish",
    "price": 350.00,
    "image": "https://i.redd.it/8oxnulzkqza11.jpg",
    quantity: 1,
  },
  {
    "id": 7,
    "name": "Vegetable Stir Fry",
    "price": 450.00,
    "image": "https://1.bp.blogspot.com/-2J063KVNWTE/WkWDs7d9M-I/AAAAAAAAycQ/sWpbgBX9aAQLwvcwRUE-eLZ-FdXPYfEdgCLcBGAs/s1600/Fried-chicken-biryani.jpg",
    quantity: 1,
  },
  {
    "id": 8,
    "name": "Chiken briyani",
    "price": 350.00,
    "image": "https://tse3.mm.bing.net/th?id=OIP.wAYAsdFMHBbmXP_Tzk4NdgHaEp&pid=Api&P=0&h=180",
    quantity: 1,
  },
  {
    "id": 9,
    "name": "Fish Tacos",
    "price": 250.00,
    "image": "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/amina/Fish_fry_original_1_edit.jpg",
    quantity: 1,
  },
  {
    "id": 10,
    "name": "GollGapa",
    "price": 100.00,
    "image": "https://static.toiimg.com/photo/75831269.cms",
    quantity: 1,
  },
  {
    "id": 11,
    "name": "Margherita Pizza",
    "price": 199.50,
    "image": "https://www.engelvoelkers.com/wp-content/uploads/2014/07/pizza-stock.jpg",
    quantity: 1,
  },
  {
    "id":12,
    "name": "Classic Burger",
    "price": 99.00,
    "image": "https://i0.wp.com/thenutritionadventure.com/wp-content/uploads/2017/07/PourHouseAmericanBurger.jpg?resize=5236%2C3490",
    quantity: 1,
  },
  {
    "id": 13,
    "name": "Age Roll",
    "price": 100.00,
    "image": "https://tse4.mm.bing.net/th?id=OIP.LKxzPBKYuBR_2tFwuBh98QHaF3&pid=Api&P=0&h=180",
    quantity: 1,
  },
  {
    "id": 14,
    "name": "Thali full Punjabi",
    "price": 250.00,
    "image": "https://en-media.thebetterindia.com/uploads/2016/08/guj-Copy.jpeg",
    quantity: 1,
  },
  {
    "id": 15,
    "name": "Maggi",
    "price": 65.50,
    "image": "https://i0.wp.com/dishesandflavors.com/wp-content/uploads/2021/01/Veg-Chow-Mein.jpg?resize=800%2C600&ssl=1&is-pending-load=1",
    quantity: 1,
  },
  {
    "id": 16,
    "name": "Caesar  Fish",
    "price": 350.00,
    "image": "https://i.redd.it/8oxnulzkqza11.jpg",
    quantity: 1,
  },
  {
    "id": 17,
    "name": "Vegetable Stir Fry",
    "price": 450.00,
    "image": "https://1.bp.blogspot.com/-2J063KVNWTE/WkWDs7d9M-I/AAAAAAAAycQ/sWpbgBX9aAQLwvcwRUE-eLZ-FdXPYfEdgCLcBGAs/s1600/Fried-chicken-biryani.jpg",
    quantity: 1,
  },
  {
    "id": 18,
    "name": "Chiken briyani",
    "price": 350.00,
    "image": "https://tse3.mm.bing.net/th?id=OIP.wAYAsdFMHBbmXP_Tzk4NdgHaEp&pid=Api&P=0&h=180",
    quantity: 1,
  },
  {
    "id": 19,
    "name": "Fish Tacos",
    "price": 250.00,
    "image": "https://www.archanaskitchen.com/images/archanaskitchen/1-Author/amina/Fish_fry_original_1_edit.jpg",
    quantity: 1,
  },
  {
    "id": 20,
    "name": "GollGapa",
    "price": 100.00,
    "image": "https://static.toiimg.com/photo/75831269.cms",
    quantity: 1,
  }
]
